#!/bin/sh
#

# record audio
AUDIO="$(date).wav"

ffmpeg -y -f alsa -i hw:1 -acodec pcm_s16le -ac 1 -ar 44100 -t 7 -f wav "$AUDIO"

CMD="$(python3 stt.py "./$AUDIO")"

IMG="$(date).jpg"
IMG="bus.jpg"

# ffmpeg -i /dev/video0 -frames:v 1 "$IMG"

python3 api.py "./$IMG" "$CMD help me navigate giving me directions specifying aproximate distances and tips because i'm blind keep max 40 words long"

# rm "$IMG"

rm "$AUDIO"
